services:
  app:
    build:
      context: .
      target: develop
      tags:
        - botmask:develop
    image: botmask:develop
    container_name: botmask
    stdin_open: true
    tty: true
    env_file: .env
    ports:
      - 9222:9223
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /run/user/1000/wayland-0:/run/user/1000/wayland-0
      - cache:/root/.cache

volumes:
  cache: