services:
  app:
    build:
      target: deploy
      tags:
        - botmask:deploy
    image: botmask:deploy
    environment:
      VIRTUAL_DISPLAY: "true"
      BROWSER_ARGS: "--ignore-gpu-blocklist --disable-blink-features=AutomationControlled --disable-dev-shm-usage --no-sandbox --disable-setuid-sandbox --disable-features=IsolateOrigins,site-per-process --disable-site-isolation-trials"
    ports:
      - 6080:6080
      - 5900:5900